# Generated by Django 5.2.6 on 2025-10-19 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('benchmark_performance', models.IntegerField()),
                ('dataset_size', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('img', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('FORMED', 'Formed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('creation_datatime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('complition_datetime', models.DateTimeField(blank=True, null=True)),
                ('batch_size', models.IntegerField(default=64, validators=[django.core.validators.MinValueValidator(1)])),
                ('epochs', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_aimodels', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_aimodels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetInAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpus_cnt', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('fitting_time', models.FloatField(blank=True, null=True)),
                ('aimodel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='binded_aimodels', to='app_for_lab1.aimodel')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='binded_datasets', to='app_for_lab1.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'aimodel')},
            },
        ),
    ]
