# Generated by Django 5.2.6 on 2025-09-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_lab1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
