# Generated by Django 5.2.6 on 2025-09-20 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_lab1', '0004_alter_dataset_img_aimodel_datasetinaimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='batch_size',
            field=models.IntegerField(default=64, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimodel',
            name='epochs',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
