# Generated by Django 5.2.6 on 2025-09-20 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_lab1', '0005_aimodel_batch_size_aimodel_epochs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='batch_size',
            field=models.IntegerField(default=64, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='epochs',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
