# Generated by Django 5.2.6 on 2025-09-28 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_lab1', '0007_alter_dataset_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetinaimodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='datasetinaimodel',
            name='gpus_cnt',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
