# Generated by Django 5.2.6 on 2025-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_lab1', '0008_remove_datasetinaimodel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetinaimodel',
            name='fitting_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
